name: Fetch Discord Logs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Discord logs
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
      run: |
        python main.py

