name: Discord Log Fetcher

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  fetch_discord_log:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Discord Log
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
      run: |
        python main.py

    - name: Archive log file
      uses: actions/upload-artifact@v2
      with:
        name: discord-log
        path: discord_log_*.txt

