name: Fetch Discord Logs

on:
  workflow_dispatch:

jobs:
  fetch_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py pytz

      - name: Run the script
        env:
          DISCORD_TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
        run: python fetch_discord_logs.py

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: discord-logs
          path: discord_log_*.txt
